### ISSUE TITLE
Unable to generate any output

### ISSUE THREAD

**Issue by Chris-M-P** [haghish/rcall#1]
I've got Stata 14.1IC and various versions of R (3.2.2, 3.2.3, 3.2.5, 3.3.0) which all work fine, but I can't get any output from Rcall (Windows 7 machine). I've used 'setpath' for different versions of R with no joy - no output and no error messages. I get a brief flash of blue output screen which disappears before I can see any message.

A possible issue could be that I used 'setpath' to define the path before trying the default setting - can this be reset?

**Comment by haghish** [comment]
The blue screen is from the Shell command. Have you seen these documentations? 
http://www.haghish.com/packages/Rcall.php

- What is your R path?

**Comment by haghish** [comment]
The **pkg** file that I uploaded yesterday was broken and was not installing all of the files. In fact, I had the same error this morning. It is fixed now, please reinstall the package from GitHub and confirm that it is working now

**Comment by Chris-M-P** [comment]
Yes, I've looked through the documentation and I can't get the first command to work.

My R path is: C:/Program Files/R/R-3.2.5/bin/R.exe

I've just tried the updated version and no improvement yet - will try again tomorrow am (in case Github is a bit behind).

**Comment by haghish** [comment]
GitHub is not behind. It's working for me. 

Do me a favor. First confirm that your computer can run R in batch mode. Here is a quick example. Create an R script file and execute it in batch mode with your given path. If it works, then I have to figure out what's wrong with the package in Windows. 

https://akastrin.wordpress.com/2009/06/18/batch-processing-with-r/

**Comment by PatrickJohnston** [comment]
Similar issue on OS X with R 3.3.1 installed from CRAN.

**Comment by haghish** [comment]
I barely think the problem is because of R version. For me it works perfectly fine on both **3.2.4** and **3.3.1**. I am using OS X **10.10.3**. We are running R in batch mode so the version is not a problem here. 

It's also probably not a Stata problem, because it works FINE on my Stata 13.1 and 14.1.

**Comment by haghish** [comment]
Ok **I think I fixed the bug**. There was an error with defining the path permanently. I fixed it now.
- make sure you remove the package and reinstall it again. You should have no problem with defining the path to R now. 

another point. I added a **debug** subcommand which helps figuring out problems. It is documented in the help file, so in case this update does not solve your problem, apply the **debug** subcommand and share the information here.

**Comment by aghaynes** [comment]
I'm having this issue too. I installed Rcall a few mins ago and get this:
R: debug setpath "C:\Program Files\R\R-3.2.3\bin\i386\Rterm.exe"

Debug mode
Running R in debug mode
Memorizing R path
the Rpath.ado was created to memorize the path to    C:\Program invalid name
r(198);

I've tried all of the different exes in the directory (Rscript, Rterm,...) and none of them seem to work.

**Comment by aghaynes** [comment]
I think I see the problem... its the space in the directory path. Stata is not good at handing spaces in strings and, by default, windows puts a space in the program files directory name...

**Comment by Chris-M-P** [comment]
I've tracked down these error messages from the batch script (no apparent errors using the debug command):
'CMD.exe was not started with the above path as the current directory. UNC paths are not supported. Defaulting to Windows directory.'
'Error: '\p' is an unrecognized escape character in string starting "'c:\ado\p" execution halted'

**Comment by haghish** [comment]
@aghaynes the problem you mentioning was from a tiny mistake in the debug mode, which I fixed now. That had nothing to do with the actual problem you guys are facing... If you reinstall the package now, you should be able to run the debug mode just fine. 

@PatrickJohnston The last night update should solve your problem, given that you are a Mac user. There was a bug in the memory file of the Rpath.ado which I fixed. 

@Chris-M-P Cool. That is useful. So you actually failed to run **R** in batch mode, [following the instructions given in this link](https://akastrin.wordpress.com/2009/06/18/batch-processing-with-r/). That is both Good and Bad news. Good because the problem is no-longer related to **Rcall** package and more related to the OS. Bad because I can't really help until you figure out how to run **R** in batch mode on your machine and I will figure out a way to facilitate it.   

I don't have a windows machine at the moment...

**Comment by aghaynes** [comment]
After deleting the 7 files and reinstalling, I'm still getting the same message:
R: debug setpath "C:\Program Files\R\R-3.2.3\bin\i386\Rterm.exe"

Debug mode
Running R in debug mode
Memorizing R path
the Rpath.ado was created to memorize the path to    C:\Program invalid name
r(198);

**Comment by haghish** [comment]
@aghaynes  sorry mate. just "pushed" the changes to GitHub. Try it now, it should work

**Comment by aghaynes** [comment]
OK. The debug now works.

This is the R code generated by Rcall...

a <- rnorm(10)
source('c:\ado\plus/s/stata.output.R')
stata.output()
rm(stata.output)

The problem is that R interprets \ as an escape character: it looks at the path and "says" to itself, "ahha, \p is something special, but I do not know what." (it's probably doing the same with \a...). RCall needs to either exchange \ for / or for \\. I think that should/might solve (part) it...

**Comment by haghish** [comment]
@aghaynes Alright, that's easy to fix but I believe @Chris-M-P  is having a different problem. Anyways, 
I updated Rcall.ado to change the path to the **stata.output.R** in windows. Give it another try!

**Comment by aghaynes** [comment]
Thats still not it, now you change all forward slashes to backslashes. If you have backslashes in R, they need to be double backslashes (backslash is the escape character)
  a <- rnorm(10)
source('c:\ado\plus\s\stata.output.R')
stata.output()
rm(stata.output)

It should be either
source('c:\\ado\\plus\\s\\stata.output.R')
or
source('c:/ado/plus/s/stata.output.R')

Regarding @Chris-M-P's issue, note the last line : 'Error: '\p' is an unrecognized escape character in string starting "'c:\ado\p" execution halted'
It's trying to do something with the p, but it doesn't know what to do... ;)

**Comment by Chris-M-P** [comment]
@haghish Yes - I seem to be having problems of my own running R in batch mode. We could close this issue and you all carry on in another issue? BTW - looking forward to getting it working though!

**Comment by haghish** [comment]
@aghaynes @Chris-M-P  Thanks. I realized that too... Both problems should be solved now. Please confirm that. uninstall and reinstall the package...

**Comment by aghaynes** [comment]
Seems to be working for me now (only tried a small vector though) ;) 
Thanks @haghish!

**Comment by PatrickJohnston** [comment]
After reinstalling it, it is now working for me. Thanks! (Fwiw, the error Stata threw initially was that it couldn't find R in /usr/bin. My R is in /usr/local/bin. I was still getting bugs after changing the path in the ado file, however.) Anyway, thanks again for the fix on this!

**Comment by Chris-M-P** [comment]
Yep - working here too. Thanks @haghish

**Comment by haghish** [comment]
Yeah everybody happy now! enjoy **R**, **C++**, **JavaScript**, etc... interactively in Stata!
