### ISSUE TITLE
github install haghish/rcall, version("2.5.0"): error: file not found

### ISSUE THREAD

**Issue by georgehuangcool** [haghish/rcall#34]
Hello, when I try to run

`github install haghish/rcall, version("2.5.0")`

I got error:

file not found
    rcall-2.5.0\.gitignore (???????????)

**Comment by haghish** [comment]
I'm unsure why you cannot install a certain version. You could look in the working directory and check whether you have the permission to download files in there. This error could be caused in so many ways. It even can be due to your Stata version, operating system, etc. In any way, you can also download an file locally and install it with `github` command.
